version: '3'
services:
  client-app:
    build: ./client
    volumes:
      - ./client:/app
    image: client-todo
    container_name: client-todo
    ports:
      - '3000:3000'
  backend-app:
    build: ./backend
    volumes:
      - ./backend:/app
    image: backend-todo
    container_name: backend-todo
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./data:/data/db
    command: mongod --logpath /dev/null
